apiVersion: apps/v1
kind: Deployment
metadata:
  name: ado-agent
  namespace: ado-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ado-agent
  template:
    metadata:
      labels:
        app: ado-agent
    spec:
      containers:
      - name: ado-agent
        image: 28may1988/azp-agent:linux
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: ado-agent-secret
      imagePullSecrets:
      - name: dockerhub-secret
[ec2-user@ip-172-31-3-204 AD0-Keda]$ cat dockerhub-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: ado-agent
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsicGFzc3dvcmQiOiIyOUFwcmlsQCMpQCEiLCJ1c2VybmFtZSI6IjI4bWF5MTk4OCIsImVtYWlsIjoia2tyZWRkeWkucC5zQGdtYWlsLmNvbSIsImF1dGgiOiJCd0RBT0NBZ1pBQUFBQUFBQUJBT0FBQUFBQUFBQUNBQUFBQUFBQUFBQUFBQUFBQUFBQUF3Z0FBQUFBIn19fQ==
