apiVersion: v1
kind: Secret
metadata:
  name: pipeline-auth
  namespace: ado-agent
type: Opaque
data:
  personalAccessToken: MlJ1V2wyS3VybG9KTENoMW94NXIwQ2ljSXNnejRWREVBb2NheWJRWExGamNZMkpoZGhDd0pRUUo5OUJEQUNBQUFBQU5zbktNQUFBU0FaRE8zZXQz
  AZP_URL: aHR0cHM6Ly9kZXYuYXp1cmUuY29tLzNhbmdlbHNpbnYv
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: pipeline-trigger-auth
  namespace: ado-agent
spec:
  secretTargetRef:
    - parameter: personalAccessToken
      name: pipeline-auth
      key: personalAccessToken
    - parameter: organizationURL
      name: pipeline-auth
      key: AZP_URL
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ado-agent-scaler
  namespace: ado-agent
spec:
  scaleTargetRef:
    name: ado-agent
  minReplicaCount: 0
  maxReplicaCount: 5
  pollingInterval: 10
  cooldownPeriod: 60
  triggers:
    - type: azure-pipelines
      metadata:
        poolID: "11"
        organizationURLFromEnv: "AZP_URL"
      authenticationRef:
        name: pipeline-trigger-auth
